/**
 * Recommendation types generated by the engine
 */
export enum RecommendationType {
  /** Member is close to a higher rate tier */
  BALANCE_TIER_NUDGE = 'BALANCE_TIER_NUDGE',
  /** Suggest optimal term based on rate environment */
  TERM_OPTIMIZATION = 'TERM_OPTIMIZATION',
  /** Suggest splitting into a ladder */
  LADDER_SUGGESTION = 'LADDER_SUGGESTION',
  /** Cross-sell to non-certificate product */
  PRODUCT_CROSS_SELL = 'PRODUCT_CROSS_SELL',
  /** Loyalty renewal with premium rate */
  LOYALTY_RENEWAL = 'LOYALTY_RENEWAL',
  /** Default: renew at FI-preferred term */
  DEFAULT_RENEWAL = 'DEFAULT_RENEWAL',
}

/**
 * A recommendation generated for a specific certificate at maturity
 */
export interface Recommendation {
  recId: string;
  certId: string;
  memberId: string;
  recType: RecommendationType;
  priority: number; // 1 = primary, 2 = secondary, etc.
  title: string;
  description: string;
  rationale: string;
  details: RecommendationDetails;
  shownAt: string | null; // ISO 8601
  accepted: boolean;
  acceptedAt: string | null; // ISO 8601
  dismissed: boolean;
  dismissedAt: string | null; // ISO 8601
  createdAt: string; // ISO 8601
}

/**
 * Type-specific recommendation details
 */
export type RecommendationDetails =
  | BalanceTierNudgeDetails
  | TermOptimizationDetails
  | LadderSuggestionDetails
  | ProductCrossSellDetails
  | LoyaltyRenewalDetails
  | DefaultRenewalDetails;

export interface BalanceTierNudgeDetails {
  type: 'balance_tier_nudge';
  currentBalance: number;
  tierThreshold: number;
  amountNeeded: number;
  currentRate: number;
  tierRate: number;
  projectedEarnings: number;
  termMonths: number;
}

export interface TermOptimizationDetails {
  type: 'term_optimization';
  suggestedTermMonths: number;
  suggestedRate: number;
  currentRate: number;
  rateDifference: number;
  projectedEarnings: number;
}

export interface LadderSuggestionDetails {
  type: 'ladder_suggestion';
  suggestedSplits: number;
  terms: number[];
  weightedRate: number;
  totalEarnings: number;
  firstAccessMonths: number;
}

export interface ProductCrossSellDetails {
  type: 'product_cross_sell';
  productType: string;
  productName: string;
  productRate: number;
  benefits: string[];
}

export interface LoyaltyRenewalDetails {
  type: 'loyalty_renewal';
  standardRate: number;
  loyaltyRate: number;
  premiumBps: number; // basis points above standard
  termMonths: number;
  projectedEarnings: number;
}

export interface DefaultRenewalDetails {
  type: 'default_renewal';
  termMonths: number;
  rate: number;
  projectedEarnings: number;
}
